"""added String values for local

Revision ID: 8d37f19fd174
Revises: 7ccc775b5e4f
Create Date: 2023-01-15 16:41:19.213444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d37f19fd174'
down_revision = '7ccc775b5e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('destiny', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.drop_column('destiny')
        batch_op.drop_column('origin')

    # ### end Alembic commands ###
