"""Initial migration.

Revision ID: ed517bb4ebc8
Revises: 
Create Date: 2023-01-07 17:30:03.626694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed517bb4ebc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride_request', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_ride_request_user_id'), ['user_id', 'ride_id'])

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_vehicle_license_plate'), ['license_plate'])
        batch_op.create_foreign_key(batch_op.f('fk_vehicle_model_id_model'), 'model', ['model_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_vehicle_model_id_model'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_vehicle_license_plate'), type_='unique')
        batch_op.drop_column('model_id')

    with op.batch_alter_table('ride_request', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_ride_request_user_id'), type_='unique')

    # ### end Alembic commands ###
